"""Hades report model.

`HadesReport` is the single result container that every Hades phase
writes into. The markdown + JSON serializers live here so the report
shape has exactly one definition across the package.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Dict, List


class HadesReport:
    """Report generated by a Hades run.

    Each field corresponds to one pipeline phase. Phases fill what they
    produce; the markdown/JSON serializers render what's there. This
    shape is part of the public API: the morning briefing, the notif
    script, and any external dashboards depend on these field names.
    """

    def __init__(self) -> None:
        self.timestamp: str = datetime.now(timezone.utc).isoformat()
        self.health: Dict[str, Any] = {
            "codexes": {},
            "chroma_vs_fs": {},
            "orphans": {"chroma_only": [], "fs_unembedded": []},
            "missing_indexes": [],
            "stale_candidates": [],
        }
        self.distillation: Dict[str, Any] = {
            "sessions_processed": 0,
            "distilled_files_written": 0,
            "by_codex": {},
        }
        self.archive: Dict[str, Any] = {
            "files_archived": 0,
            "errors": [],
        }
        self.suggestions: List[Dict] = []
        self.embed: Dict[str, Any] = {}
        self.errors: List[str] = []

    def to_dict(self) -> Dict:
        return {
            "timestamp": self.timestamp,
            "health": self.health,
            "distillation": self.distillation,
            "archive": self.archive,
            "embed": self.embed,
            "suggestions": self.suggestions,
            "errors": self.errors,
        }

    def to_markdown(self) -> str:
        """Format the report as a human-readable markdown summary.

        Each section is conditionally rendered based on whether the
        corresponding phase produced output. Empty phases don't show —
        keeps the report tight when most things are fine.
        """
        lines: List[str] = [
            f"# 🌙 Hades Nightly Report — {self.timestamp[:10]}",
            "",
            "## 📊 Codex Overview",
            "| Codex | Files | Embedded | Distilled | Sessions | Missing INDEX |",
            "|---|---|---|---|---|---|",
        ]

        for codex, info in sorted(self.health.get("codexes", {}).items()):
            missing = "⚠️" if codex in self.health.get("missing_indexes", []) else "✅"
            lines.append(
                f"| {codex} | {info.get('files', 0)} | {info.get('embedded', '?')} | "
                f"{info.get('distilled', 0)} | {info.get('sessions', 0)} | {missing} |"
            )

        lines.append("")

        # Chroma vs FS consistency
        orphans_fs = self.health.get("orphans", {}).get("fs_unembedded", [])
        orphans_c = self.health.get("orphans", {}).get("chroma_only", [])
        if orphans_fs or orphans_c:
            lines.append("## ⚠️ Consistency Issues")
            if orphans_fs:
                lines.append(f"- **{len(orphans_fs)} files not embedded in ChromaDB**")
            if orphans_c:
                lines.append(f"- **{len(orphans_c)} ChromaDB entries orphaned** (no matching file)")

        # Missing INDEXes
        missing = self.health.get("missing_indexes", [])
        if missing:
            lines.append(f"\n### Missing INDEX.md ({len(missing)})")
            for m in missing:
                lines.append(f"- {m}")

        # INDEX auto-creation report
        created = self.health.get("indexes_created", [])
        if created:
            lines.append(f"\n### ✅ INDEX.md Auto-Created ({len(created)})")
            for c in created:
                lines.append(f"- `{c}/INDEX.md` created")

        # Stale candidates
        stale = self.health.get("stale_candidates", [])
        if stale:
            lines.append(f"\n### 🗄️ Stale Candidates ({len(stale)})")
            lines.append("Files not modified in 90+ days:")
            for s in stale[:10]:
                lines.append(f"- {s['path']} (last modified: {s['last_modified'][:10]})")
            if len(stale) > 10:
                lines.append(f"- ... and {len(stale) - 10} more")

        # Suggestions
        suggestions = self.suggestions
        if suggestions:
            lines.append(f"\n## 💡 New Codex Suggestions ({len(suggestions)})")
            for s in suggestions:
                lines.append(f"- **{s.get('suggested_codex')}**: {s.get('reason', '')[:100]}")

        # Distillation summary
        dist = self.distillation
        if dist.get("distilled_files_written", 0) > 0:
            lines.append(f"\n## 🔄 Distillation")
            lines.append(f"- Sessions processed: {dist.get('sessions_processed', 0)}")
            lines.append(f"- Distilled files written: {dist.get('distilled_files_written', 0)}")

        # Embed backfill summary
        embed = self.embed
        if embed.get("embedded", 0) > 0:
            lines.append(f"\n## ⚡ Embed Backfill")
            lines.append(f"- Files embedded: {embed.get('embedded', 0)}")
            lines.append(f"- Failed: {embed.get('failed', 0)}")
            lines.append(f"- Remaining unembedded: {embed.get('remaining', 0)}")
        elif embed.get("skipped") == -1:
            lines.append(f"\n## ⚡ Embed Backfill")
            lines.append("- Embedder not available — skipped")
        elif embed.get("remaining", 0) > 0 or embed.get("failed", 0) > 0:
            lines.append(f"\n## ⚡ Embed Backfill")
            lines.append(f"- Remaining unembedded: {embed.get('remaining', 0)}")
            lines.append(f"- Failed: {embed.get('failed', 0)}")

        # Archive summary
        arch = self.archive
        if arch.get("files_archived", 0) > 0:
            lines.append(f"\n## 📦 Archive")
            lines.append(f"- Files archived: {arch.get('files_archived', 0)}")

        # Errors
        if self.errors:
            lines.append(f"\n## ❌ Errors ({len(self.errors)})")
            for e in self.errors:
                lines.append(f"- {e}")

        lines.append("")
        lines.append("---")
        lines.append(f"_Report generated: {self.timestamp}_")

        return "\n".join(lines)
