"""Hades — nightly Athenaeum consolidation pipeline.

Runs as a cron job. Performs:
  1. Distillation — extract canonical knowledge from vault sessions
  2. Health checks — ChromaDB vs filesystem consistency, INDEX coverage
  3. Archive management — identify and move stale/unlinked content
  4. Report generation — summary for the 7am delivery
"""

from __future__ import annotations

import json
import logging
import os
import re
import shutil
import time
from collections import defaultdict
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import httpx

logger = logging.getLogger(__name__)

_REAL_HOME = os.path.expanduser("~konan")
ATHENAEUM_ROOT = Path(f"{_REAL_HOME}/athenaeum")
CHROMA_DIR = Path(f"{_REAL_HOME}/.hermes/pantheon/chroma")
GRAPH_DB = Path(f"{_REAL_HOME}/.hermes/pantheon/graph.db")
SUGGEST_FILE = Path(f"{_REAL_HOME}/.hermes/pantheon/suggested-codexes.json")
HERMES_INBOX = Path(f"{_REAL_HOME}/pantheon/gods/messages/hermes")
INDEX_DESCRIPTION = (
    "Content in `{path}` is managed by Demeter and Mnemosyne.\n"
    "Files are auto-detected and embedded into the vector store on change."
)

# Files older than this (in days) are archive candidates if not linked in the graph
STALE_THRESHOLD_DAYS = 90

# Codex exclusion list — system codices we don't auto-archive or auto-distill
SYSTEM_CODEXES = {"Codex-Pantheon"}

KNOWN_CODEXES = [
    "Codex-Forge", "Codex-Pantheon", "Codex-Infrastructure",
    "Codex-SKC", "Codex-Fiction", "Codex-Asclepius", "Codex-General",
]

EMBEDDABLE_EXTS = {".md", ".txt", ".json", ".yaml", ".yml"}
DISTILLED_DIR_NAME = "distilled"
ARCHIVE_DIR_NAME = "archive"
SESSIONS_DIR_NAME = "sessions"


# ---------------------------------------------------------------------------
# Result container
# ---------------------------------------------------------------------------


class HadesReport:
    """Report generated by a Hades run."""

    def __init__(self):
        self.timestamp: str = datetime.now(timezone.utc).isoformat()
        self.health: Dict[str, Any] = {
            "codexes": {},
            "chroma_vs_fs": {},
            "orphans": {"chroma_only": [], "fs_unembedded": []},
            "missing_indexes": [],
            "stale_candidates": [],
        }
        self.distillation: Dict[str, Any] = {
            "sessions_processed": 0,
            "distilled_files_written": 0,
            "by_codex": {},
        }
        self.archive: Dict[str, Any] = {
            "files_archived": 0,
            "errors": [],
        }
        self.suggestions: List[Dict] = []
        self.embed: Dict[str, Any] = {}
        self.errors: List[str] = []

    def to_dict(self) -> Dict:
        return {
            "timestamp": self.timestamp,
            "health": self.health,
            "distillation": self.distillation,
            "archive": self.archive,
            "embed": self.embed,
            "suggestions": self.suggestions,
            "errors": self.errors,
        }

    def to_markdown(self) -> str:
        """Format the report as a human-readable markdown summary."""
        lines = [
            f"# 🌙 Hades Nightly Report — {self.timestamp[:10]}",
            "",
            "## 📊 Codex Overview",
            "| Codex | Files | Embedded | Distilled | Sessions | Missing INDEX |",
            "|---|---|---|---|---|---|",
        ]

        for codex, info in sorted(self.health.get("codexes", {}).items()):
            missing = "⚠️" if codex in self.health.get("missing_indexes", []) else "✅"
            lines.append(
                f"| {codex} | {info.get('files', 0)} | {info.get('embedded', '?')} | "
                f"{info.get('distilled', 0)} | {info.get('sessions', 0)} | {missing} |"
            )

        lines.append("")

        # Chroma vs FS consistency
        orphans_fs = self.health.get("orphans", {}).get("fs_unembedded", [])
        orphans_c = self.health.get("orphans", {}).get("chroma_only", [])
        if orphans_fs or orphans_c:
            lines.append("## ⚠️ Consistency Issues")
            if orphans_fs:
                lines.append(f"- **{len(orphans_fs)} files not embedded in ChromaDB**")
            if orphans_c:
                lines.append(f"- **{len(orphans_c)} ChromaDB entries orphaned** (no matching file)")

        # Missing INDEXes
        missing = self.health.get("missing_indexes", [])
        if missing:
            lines.append(f"\n### Missing INDEX.md ({len(missing)})")
            for m in missing:
                lines.append(f"- {m}")

        # INDEX auto-creation report
        created = self.health.get("indexes_created", [])
        if created:
            lines.append(f"\n### ✅ INDEX.md Auto-Created ({len(created)})")
            for c in created:
                lines.append(f"- `{c}/INDEX.md` created")

        # Stale candidates
        stale = self.health.get("stale_candidates", [])
        if stale:
            lines.append(f"\n### 🗄️ Stale Candidates ({len(stale)})")
            lines.append("Files not modified in 90+ days:")
            for s in stale[:10]:
                lines.append(f"- {s['path']} (last modified: {s['last_modified'][:10]})")
            if len(stale) > 10:
                lines.append(f"- ... and {len(stale) - 10} more")

        # Suggestions
        suggestions = self.suggestions
        if suggestions:
            lines.append(f"\n## 💡 New Codex Suggestions ({len(suggestions)})")
            for s in suggestions:
                lines.append(f"- **{s.get('suggested_codex')}**: {s.get('reason', '')[:100]}")

        # Distillation summary
        dist = self.distillation
        if dist.get("distilled_files_written", 0) > 0:
            lines.append(f"\n## 🔄 Distillation")
            lines.append(f"- Sessions processed: {dist.get('sessions_processed', 0)}")
            lines.append(f"- Distilled files written: {dist.get('distilled_files_written', 0)}")

        # Embed backfill summary
        embed = self.embed
        if embed.get("embedded", 0) > 0:
            lines.append(f"\n## ⚡ Embed Backfill")
            lines.append(f"- Files embedded: {embed.get('embedded', 0)}")
            lines.append(f"- Failed: {embed.get('failed', 0)}")
            lines.append(f"- Remaining unembedded: {embed.get('remaining', 0)}")
        elif embed.get("skipped") == -1:
            lines.append(f"\n## ⚡ Embed Backfill")
            lines.append("- Embedder not available — skipped")
        elif embed.get("remaining", 0) > 0 or embed.get("failed", 0) > 0:
            lines.append(f"\n## ⚡ Embed Backfill")
            lines.append(f"- Remaining unembedded: {embed.get('remaining', 0)}")
            lines.append(f"- Failed: {embed.get('failed', 0)}")

        # Archive summary
        arch = self.archive
        if arch.get("files_archived", 0) > 0:
            lines.append(f"\n## 📦 Archive")
            lines.append(f"- Files archived: {arch.get('files_archived', 0)}")

        # Errors
        if self.errors:
            lines.append(f"\n## ❌ Errors ({len(self.errors)})")
            for e in self.errors:
                lines.append(f"- {e}")

        lines.append("")
        lines.append("---")
        lines.append(f"_Report generated: {self.timestamp}_")

        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Phase 0: Embedder service (fast embed via OpenRouter, Ollama fallback)
# ---------------------------------------------------------------------------


class _Embedder:
    """Thin embedding wrapper — OpenRouter first, Ollama fallback.

    Configurable via env vars:
      ATHENAEUM_EMBED_API_KEY  (or OPENROUTER_API_KEY)
      ATHENAEUM_EMBED_PROVIDER (set to "ollama" to force local)
      ATHENAEUM_EMBED_MODEL    (default: nomic-embed-text:v1.5)
    """

    def __init__(self):
        self._api_key = os.environ.get("ATHENAEUM_EMBED_API_KEY", "") or os.environ.get("OPENROUTER_API_KEY", "")
        self._model = "nvidia/llama-nemotron-embed-vl-1b-v2:free"
        self._timeout = 30.0
        self._ollama_model = os.environ.get("ATHENAEUM_EMBED_MODEL", "nomic-embed-text:v1.5")

    @property
    def use_openrouter(self) -> bool:
        provider = os.environ.get("ATHENAEUM_EMBED_PROVIDER", "").lower()
        if provider == "ollama":
            return False
        return bool(self._api_key)

    def embed(self, text: str) -> List[float]:
        """Embed text and return a single averaged vector."""

        def _call_api(payload: dict) -> List[float]:
            if self.use_openrouter:
                url = "https://openrouter.ai/api/v1/embeddings"
                headers = {
                    "Authorization": f"Bearer {self._api_key}",
                    "Content-Type": "application/json",
                }
            else:
                url = "http://localhost:11434/api/embeddings"
                headers = {"Content-Type": "application/json"}
                payload.setdefault("options", {})["num_ctx"] = 2048
            resp = httpx.post(url, headers=headers, json=payload, timeout=self._timeout)
            resp.raise_for_status()
            if self.use_openrouter:
                return resp.json()["data"][0]["embedding"]
            return resp.json()["embedding"]

        CHUNK_SIZE = 1500
        CHUNK_OVERLAP = 100
        MAX_CHUNKS = 20

        if len(text) <= CHUNK_SIZE:
            if self.use_openrouter:
                return _call_api({"model": self._model, "input": text})
            return _call_api({"model": self._ollama_model, "prompt": "search_document: " + text})

        # Chunk and average
        chunks = []
        start = 0
        while start < len(text) and len(chunks) < MAX_CHUNKS:
            end = min(start + CHUNK_SIZE, len(text))
            if end < len(text):
                cut = text.rfind(". ", start + CHUNK_SIZE - 200, end)
                if cut > start + CHUNK_SIZE // 2:
                    end = cut + 1
            chunks.append(text[start:end])
            start = end - CHUNK_OVERLAP if end < len(text) else end

        vectors = []
        for chunk in chunks:
            if self.use_openrouter:
                v = _call_api({"model": self._model, "input": chunk})
            else:
                v = _call_api({"model": self._ollama_model, "prompt": "search_document: " + chunk})
            vectors.append(v)

        if not vectors:
            raise RuntimeError("embedding failed for all chunks")

        dim = len(vectors[0])
        avg = [0.0] * dim
        for v in vectors:
            for i in range(dim):
                avg[i] += v[i]
        return [x / len(vectors) for x in avg]

    def is_available(self) -> bool:
        """Check if the embedder is reachable."""
        if self.use_openrouter:
            return True
        try:
            resp = httpx.get("http://localhost:11434/api/tags", timeout=5.0)
            return resp.status_code == 200
        except Exception:
            return False


def _get_chroma_client():
    """Get or create a ChromaDB PersistentClient."""
    try:
        import chromadb
        client = chromadb.PersistentClient(path=str(CHROMA_DIR))
        client.heartbeat()
        return client
    except Exception as exc:
        logger.warning("ChromaDB unavailable: %s", exc)
        return None


def _partition_for(codex: str) -> str:
    slug = codex.lower().replace("-", "_").replace(" ", "_")
    return f"pantheon_{slug}"


def _embed_file(file_path: str, content: str, codex_hint: str = "") -> bool:
    """Embed a single file into ChromaDB. Returns True on success."""
    try:
        client = _get_chroma_client()
        if client is None:
            return False

        embedder = _Embedder()
        if not embedder.is_available():
            logger.warning("  → Embedder not available — skipping %s", Path(file_path).name)
            return False

        rel = Path(file_path).relative_to(ATHENAEUM_ROOT)
        codex = codex_hint or rel.parts[0]
        col_name = _partition_for(codex)

        try:
            collection = client.get_collection(col_name)
        except Exception:
            collection = client.create_collection(col_name)

        embedding = embedder.embed(content[:4000])
        collection.upsert(
            ids=[str(Path(file_path).resolve())],
            embeddings=[embedding],
            documents=[content],
            metadatas=[{"source": file_path, "codex": codex, "filename": Path(file_path).name}],
        )
        logger.info("  → Embedded: %s → %s", rel, col_name)
        return True
    except Exception as exc:
        logger.warning("  → Embed failed for %s: %s", file_path, exc)
        return False


def embed_missing_files(max_files: int = 30) -> Dict[str, Any]:
    """Backfill filesystem files not yet in ChromaDB, up to max_files per run.
    
    Walks each Codex, checks ChromaDB via per-collection query (not full dump),
    and embeds any missing files. Capped at max_files to avoid runaway runtime.
    
    Args:
        max_files: Max files to embed per run (default 200).
    
    Returns: {
        "embedded": int,      # files newly embedded
        "skipped": int,       # files skipped (unavailable embedder)
        "failed": int,        # files that errored
        "remaining": int,     # files still unembedded (estimate)
        "total_before": int,  # vectors in ChromaDB before backfill
        "total_after": int,   # vectors in ChromaDB after backfill
    }
    """
    result: Dict[str, Any] = {
        "embedded": 0,
        "skipped": 0,
        "failed": 0,
        "remaining": 0,
        "total_before": 0,
        "total_after": 0,
    }

    client = _get_chroma_client()
    if client is None:
        logger.error("ChromaDB unavailable — cannot embed missing files")
        return result

    embedder = _Embedder()
    if not embedder.is_available():
        logger.warning("Embedder not available — skipping embed backfill")
        result["skipped"] = -1
        return result

    # Count existing vectors
    total_before = sum(col.count() for col in client.list_collections())
    result["total_before"] = total_before

    # Walk filesystem, check each file against ChromaDB, embed if missing
    for codex_dir in sorted(ATHENAEUM_ROOT.iterdir()):
        if not codex_dir.is_dir() or not codex_dir.name.startswith("Codex-"):
            continue
        codex = codex_dir.name
        col_name = _partition_for(codex)

        # Get or create the ChromaDB collection for this codex
        try:
            collection = client.get_collection(col_name)
        except Exception:
            collection = client.create_collection(col_name)

        for f in codex_dir.rglob("*"):
            if not f.is_file():
                continue
            if f.suffix.lower() not in EMBEDDABLE_EXTS:
                continue
            if f.name == "INDEX.md":
                continue
            rel = f.relative_to(ATHENAEUM_ROOT)
            parts = rel.parts
            if len(parts) > 1 and parts[1] in (ARCHIVE_DIR_NAME, DISTILLED_DIR_NAME, SESSIONS_DIR_NAME):
                continue

            abs_path = str(f.resolve())

            # Check if already embedded via per-file lookup
            try:
                existing = collection.get(ids=[abs_path])
                if existing and existing.get("ids"):
                    continue
            except Exception:
                pass

            # Read + embed
            try:
                content = f.read_text(encoding="utf-8")
            except Exception:
                result["failed"] += 1
                continue

            ok = _embed_file(abs_path, content, codex)
            if ok:
                result["embedded"] += 1
            else:
                result["failed"] += 1

            # Check cap
            if result["embedded"] + result["failed"] >= max_files:
                break

        if result["embedded"] + result["failed"] >= max_files:
            break

    # Compute remaining (approximate: count how many files still not in chroma)
    remaining = 0
    for codex_dir in sorted(ATHENAEUM_ROOT.iterdir()):
        if not codex_dir.is_dir() or not codex_dir.name.startswith("Codex-"):
            continue
        try:
            col = client.get_collection(_partition_for(codex_dir.name))
        except Exception:
            col = None
        for f in codex_dir.rglob("*"):
            if not f.is_file() or f.suffix.lower() not in EMBEDDABLE_EXTS:
                continue
            if f.name == "INDEX.md":
                continue
            rel = f.relative_to(ATHENAEUM_ROOT)
            parts = rel.parts
            if len(parts) > 1 and parts[1] in (ARCHIVE_DIR_NAME, DISTILLED_DIR_NAME, SESSIONS_DIR_NAME):
                continue
            abs_path = str(f.resolve())
            try:
                if col:
                    existing = col.get(ids=[abs_path])
                    if not existing or not existing.get("ids"):
                        remaining += 1
            except Exception:
                remaining += 1
    result["remaining"] = remaining

    # Re-count after backfill
    try:
        client2 = _get_chroma_client()
        if client2:
            result["total_after"] = sum(col.count() for col in client2.list_collections())
        else:
            result["total_after"] = result["total_before"]
    except Exception:
        result["total_after"] = result["total_before"]

    return result


def _recheck_embedded_counts(report: HadesReport) -> None:
    """Re-read ChromaDB counts and update the report's health data with accurate embedded numbers.
    
    Builds a lookup from collection name → codex name by matching KNOWN_CODEXES
    via _partition_for(), which avoids the capitalization roundtrip problem.
    
    Must be called AFTER embed_missing_files() so the report reflects post-embed state.
    """
    try:
        import chromadb
        client = chromadb.PersistentClient(path=str(CHROMA_DIR))

        # Build reverse map: partition name → codex name (e.g. pantheon_codex_skc → Codex-SKC)
        partition_to_codex: Dict[str, str] = {}
        for codex_name in list(report.health.get("codexes", {}).keys()):
            partition_to_codex[_partition_for(codex_name)] = codex_name

        # Also scan for any codexes in KNOWN_CODEXES not yet in the report
        for codex_name in list(KNOWN_CODEXES):
            if codex_name not in partition_to_codex:
                partition_to_codex[_partition_for(codex_name)] = codex_name

        # Read ChromaDB collections and map back to codex names
        chroma_counts: Dict[str, int] = {}
        for col in client.list_collections():
            codex_name = partition_to_codex.get(col.name)
            if codex_name:
                chroma_counts[codex_name] = col.count()

        # Update each codex entry with real embedded count
        for codex_name, info in report.health.get("codexes", {}).items():
            info["embedded"] = chroma_counts.get(codex_name, 0)

        # Regenerate fs_unembedded from actual state
        orphans = report.health.setdefault("orphans", {"chroma_only": [], "fs_unembedded": []})
        fs_unembedded = []
        for codex_name, info in report.health.get("codexes", {}).items():
            embeddable = info.get("embeddable", 0)
            embedded = info.get("embedded", 0)
            if embeddable > embedded:
                codex_dir = ATHENAEUM_ROOT / codex_name
                if codex_dir.is_dir():
                    for f in codex_dir.rglob("*"):
                        if not f.is_file() or f.suffix.lower() not in EMBEDDABLE_EXTS:
                            continue
                        if f.name == "INDEX.md":
                            continue
                        rel = f.relative_to(ATHENAEUM_ROOT)
                        parts = rel.parts
                        if len(parts) > 1 and parts[1] in (ARCHIVE_DIR_NAME, DISTILLED_DIR_NAME, SESSIONS_DIR_NAME):
                            continue
                        abs_p = str(f.resolve())
                        try:
                            col = client.get_collection(_partition_for(codex_name))
                            existing = col.get(ids=[abs_p])
                            if not existing or not existing.get("ids"):
                                fs_unembedded.append(str(rel))
                        except Exception:
                            fs_unembedded.append(str(rel))
                        if len(fs_unembedded) >= 50:
                            break
        orphans["fs_unembedded"] = fs_unembedded

    except Exception as exc:
        logger.warning("Failed to recheck embedded counts: %s", exc)


# ---------------------------------------------------------------------------
# 1. Health checks
# ---------------------------------------------------------------------------


def _walk_codex_files(codex_root: Path) -> Dict[str, List[Path]]:
    """Walk a Codex directory and group files by subfolder.

    Returns: {
        "files": [all embeddable files excluding archive/distilled/sessions],
        "embeddable": [files that should be in ChromaDB],
        "sessions": [session log files],
        "distilled": [existing distilled files],
        "subdirs": [all subdirectories],
    }
    """
    result: Dict[str, List[Path]] = {
        "files": [],
        "embeddable": [],
        "sessions": [],
        "distilled": [],
        "subdirs": [],
    }

    for child in codex_root.iterdir():
        if child.is_dir():
            result["subdirs"].append(child)

    for f in codex_root.rglob("*"):
        if not f.is_file():
            continue
        ext = f.suffix.lower()
        rel = f.relative_to(codex_root)
        parts = rel.parts

        # Skip hidden files
        if f.name.startswith("."):
            continue
        # Skip INDEX.md — navigation, not content
        if f.name == "INDEX.md":
            continue

        # Categorize by subfolder
        if len(parts) > 1:
            parent = parts[0]
            if parent == ARCHIVE_DIR_NAME:
                continue  # Skip archive files entirely
            if parent == DISTILLED_DIR_NAME:
                result["distilled"].append(f)
                continue
            if parent == SESSIONS_DIR_NAME:
                result["sessions"].append(f)
                continue

        result["files"].append(f)
        if ext in EMBEDDABLE_EXTS:
            result["embeddable"].append(f)

    return result


def ensure_index_files(codex_root: Path) -> List[str]:
    """Auto-create INDEX.md for any subdirectory that's missing one.

    Returns a list of paths where INDEX.md was created.
    Also checks for file counts and content changes.
    """
    created = []
    parent_name = codex_root.name
    parent_rel = f"../INDEX.md"

    for child in sorted(codex_root.iterdir()):
        if not child.is_dir() or child.name.startswith("."):
            continue

        index_path = child / "INDEX.md"
        if index_path.exists():
            continue

        # Count files in this subdirectory
        file_count = sum(1 for f in child.rglob("*") if f.is_file() and not f.name.startswith("."))

        # Generate description
        if child.name == "sessions":
            desc = "Session logs for this Codex."
        elif child.name == "distilled":
            desc = "Distilled knowledge extracted from session logs."
        elif child.name == "archive":
            desc = "Superseded and archived content."
        elif file_count == 0:
            desc = INDEX_DESCRIPTION.format(path=f"`{parent_name}/{child.name}`")
        else:
            desc = INDEX_DESCRIPTION.format(path=f"`{parent_name}/{child.name}`")

        content = (
            f"# {child.name.capitalize()} — Index\n"
            f"Parent: [{parent_name}]({parent_rel})\n\n"
            f"{desc}\n"
        )
        index_path.write_text(content, encoding="utf-8")
        created.append(f"{parent_name}/{child.name}")
        logger.info("  → Created INDEX.md for %s/%s", parent_name, child.name)

    return created


def find_stale_files(
    codex_root: Path, days: int = STALE_THRESHOLD_DAYS
) -> List[Dict]:
    """Find files not modified in *days* that are eligible for archival.

    Skips: INDEX.md, files already in archive/, files in sessions/.
    """
    cutoff = datetime.now(timezone.utc).timestamp() - (days * 86400)
    stale = []

    for f in codex_root.rglob("*"):
        if not f.is_file() or f.suffix.lower() not in EMBEDDABLE_EXTS:
            continue
        rel = f.relative_to(codex_root)
        parts = rel.parts
        if len(parts) > 1 and parts[0] in (ARCHIVE_DIR_NAME, SESSIONS_DIR_NAME, DISTILLED_DIR_NAME):
            continue
        if f.name == "INDEX.md":
            continue

        try:
            mtime = f.stat().st_mtime
            if mtime < cutoff:
                stale.append({
                    "path": str(rel),
                    "last_modified": datetime.fromtimestamp(mtime, tz=timezone.utc).isoformat(),
                    "size": f.stat().st_size,
                })
        except Exception:
            continue

    stale.sort(key=lambda x: x["last_modified"])
    return stale


def run_health_checks() -> Dict[str, Any]:
    """Run all health checks across the Athenaeum.

    Returns health dict matching HadesReport.health shape.
    """
    health: Dict[str, Any] = {
        "codexes": {},
        "chroma_vs_fs": {},
        "orphans": {"chroma_only": [], "fs_unembedded": []},
        "missing_indexes": [],
        "indexes_created": [],
        "stale_candidates": [],
        "chroma_count": None,
    }

    # Try to read ChromaDB for comparison
    chroma_counts: Dict[str, int] = {}
    try:
        import chromadb
        if CHROMA_DIR.is_dir():
            client = chromadb.PersistentClient(path=str(CHROMA_DIR))
            for col in client.list_collections():
                try:
                    name = col.name  # e.g. "pantheon_codex_forge"
                    # Parse the codex name back
                    parts = name.split("_", 2)
                    if len(parts) >= 3:
                        raw = parts[2]
                        words = raw.split("_")
                        codex_name = "Codex-" + "-".join(w.capitalize() for w in words) if words else "Codex-General"
                        chroma_counts[codex_name] = col.count()
                except Exception:
                    pass
        health["chroma_count"] = sum(chroma_counts.values()) if chroma_counts else None
    except ImportError:
        pass  # chromadb not available

    for codex_name in KNOWN_CODEXES:
        codex_dir = ATHENAEUM_ROOT / codex_name
        if not codex_dir.is_dir():
            continue

        info = _walk_codex_files(codex_dir)
        health["codexes"][codex_name] = {
            "files": len(info["files"]),
            "embeddable": len(info["embeddable"]),
            "sessions": len(info["sessions"]),
            "distilled": len(info["distilled"]),
            "subdirs": len(info["subdirs"]),
        }

        # Auto-create INDEX.md for missing subdirectories
        created = ensure_index_files(codex_dir)
        health["indexes_created"].extend(created)

        # Check for persistent gaps (subdirs without INDEX.md despite creation attempt)
        # This catches edge cases like empty dirs or permission issues
        still_missing = []
        for child in codex_dir.iterdir():
            if child.is_dir() and not child.name.startswith("."):
                if not (child / "INDEX.md").exists():
                    still_missing.append(f"{codex_dir.name}/{child.name}")
        if still_missing:
            health["missing_indexes"].extend(still_missing)

        # Chroma vs FS comparison
        embeddable_count = len(info["embeddable"])
        chroma_count = chroma_counts.get(codex_name, 0)
        health["chroma_vs_fs"][codex_name] = {
            "chroma": chroma_count,
            "fs_embeddable": embeddable_count,
            "delta": chroma_count - embeddable_count,
        }

        if chroma_count > embeddable_count:
            # Chroma has more than filesystem — some are orphaned
            pass  # Detailed orphan detection requires iterating IDs
        elif embeddable_count > chroma_count:
            for f in info["embeddable"]:
                health["orphans"]["fs_unembedded"].append(str(f.relative_to(ATHENAEUM_ROOT)))
                if len(health["orphans"]["fs_unembedded"]) > 50:
                    break

        # Find stale files
        stale = find_stale_files(codex_dir)
        health["stale_candidates"].extend(stale)

    return health


# ---------------------------------------------------------------------------
# 2. Distillation
# ---------------------------------------------------------------------------


def distill_sessions(codex_name: str, codex_root: Path) -> Dict[str, int]:
    """Extract distilled knowledge from session logs.

    For each session file in codex/sessions/, extracts:
    - Distinct topics mentioned (from markdown headers, bold terms, bullet points)
    - Code blocks
    - Decisions and conclusions (lines after "Decision:", "Conclusion:", etc.)

    Writes a distilled summary to codex/distilled/.
    """
    sessions_dir = codex_root / SESSIONS_DIR_NAME
    distilled_dir = codex_root / DISTILLED_DIR_NAME
    distilled_dir.mkdir(parents=True, exist_ok=True)

    sessions = sorted(sessions_dir.glob("*.md")) if sessions_dir.is_dir() else []
    files_written = 0

    # Known signal patterns for extraction
    topic_pattern = re.compile(r"^#{1,3}\s+(.+)", re.MULTILINE)
    decision_pattern = re.compile(r"^\s*(?:Decision|Conclusion|Result|Outcome|Resolution)\s*[:\-–—]\s*(.+)", re.IGNORECASE | re.MULTILINE)
    bullet_pattern = re.compile(r"^\s*[-*+]\s+(.+)", re.MULTILINE)
    bold_pattern = re.compile(r"\*\*(.+?)\*\*")
    code_block_pattern = re.compile(r"```(\w*)\n(.*?)```", re.DOTALL)

    for session_path in sessions:
        try:
            content = session_path.read_text(encoding="utf-8")
        except Exception:
            continue

        if len(content.strip()) < 200:
            continue  # Skip empty or near-empty sessions

        # Extract metadata from frontmatter
        metadata = {}
        fm_match = re.match(r"^---\n(.*?)\n---", content, re.DOTALL)
        if fm_match:
            for line in fm_match.group(1).strip().split("\n"):
                if ":" in line:
                    k, _, v = line.partition(":")
                    metadata[k.strip()] = v.strip()
            content = content[fm_match.end():]

        # Extract topics (headers)
        topics = []
        for m in topic_pattern.finditer(content):
            t = m.group(1).strip()
            if t and t not in topics:
                topics.append(t)

        # Extract decisions
        decisions = [m.group(1).strip() for m in decision_pattern.finditer(content) if m.group(1).strip()]

        # Extract bold/key terms
        key_terms = list(set(m.group(1) for m in bold_pattern.finditer(content) if m.group(1)))

        # Extract code blocks
        code_blocks = []
        for m in code_block_pattern.finditer(content):
            lang = m.group(1) or "text"
            snippet = m.group(2).strip()
            if snippet:
                code_blocks.append({"language": lang, "content": snippet[:500]})

        # Extract bullet points (first ~20)
        bullets = [m.group(1).strip() for m in bullet_pattern.finditer(content) if m.group(1).strip()][:25]

        if not topics and not decisions and not bullets:
            continue  # Nothing substantive to distill

        # Build distilled document
        session_id = session_path.stem
        lines = [
            f"# Distilled: {session_id}",
            "",
            f"Source: `{codex_name}/{SESSIONS_DIR_NAME}/{session_path.name}`",
            f"Distilled at: {datetime.now(timezone.utc).isoformat()}",
            "",
        ]

        if metadata:
            lines.append("## Metadata")
            for k, v in metadata.items():
                lines.append(f"- **{k}**: {v}")
            lines.append("")

        if topics:
            lines.append(f"## Topics ({len(topics)})")
            for t in topics[:15]:
                lines.append(f"- {t}")
            lines.append("")

        if decisions:
            lines.append(f"## Decisions / Conclusions ({len(decisions)})")
            for d in decisions:
                lines.append(f"- {d}")
            lines.append("")

        if key_terms:
            lines.append(f"## Key Terms ({len(key_terms)})")
            for t in sorted(key_terms)[:20]:
                lines.append(f"- {t}")
            lines.append("")

        if code_blocks:
            lines.append("## Code / Data")
            for cb in code_blocks[:5]:
                lines.append(f"```{cb['language']}")
                lines.append(cb['content'])
                lines.append("```")
                lines.append("")

        if bullets:
            lines.append(f"## Notes ({len(bullets)})")
            for b in bullets[:20]:
                lines.append(f"- {b}")
            lines.append("")

        # Write distilled file
        distilled_name = f"{session_id}--distilled.md"
        distilled_path = distilled_dir / distilled_name
        distilled_path.write_text("\n".join(lines), encoding="utf-8")
        files_written += 1

    return {
        "sessions_processed": len(sessions),
        "distilled_files_written": files_written,
    }


def run_distillation() -> Dict[str, Any]:
    """Run distillation across all Codices with sessions."""
    results: Dict[str, Any] = {
        "sessions_processed": 0,
        "distilled_files_written": 0,
        "by_codex": {},
    }

    for codex_name in KNOWN_CODEXES:
        codex_dir = ATHENAEUM_ROOT / codex_name
        if not codex_dir.is_dir():
            continue

        codex_result = distill_sessions(codex_name, codex_dir)
        results["sessions_processed"] += codex_result.get("sessions_processed", 0)
        results["distilled_files_written"] += codex_result.get("distilled_files_written", 0)
        results["by_codex"][codex_name] = codex_result

    return results


# ---------------------------------------------------------------------------
# 3. Archive management
# ---------------------------------------------------------------------------


def run_archive() -> Dict[str, Any]:
    """Archive stale files that are not linked in the entity graph.

    A file is a candidate if:
    - Not modified in STALE_THRESHOLD_DAYS
    - Not registered as a node in the graph (or has no edges)
    - Not already in archive/ or distilled/

    Currently: reports candidates only, does NOT auto-archive.
    (Auto-archival requires explicit opt-in to avoid data loss.)
    """
    result: Dict[str, Any] = {
        "files_archived": 0,
        "candidates": [],
        "errors": [],
    }

    cutoff = datetime.now(timezone.utc).timestamp() - (STALE_THRESHOLD_DAYS * 86400)

    # Check if graph is available to consult
    graph_available = GRAPH_DB.exists()

    for codex_name in KNOWN_CODEXES:
        codex_dir = ATHENAEUM_ROOT / codex_name
        if not codex_dir.is_dir() or codex_name in SYSTEM_CODEXES:
            continue

        for f in codex_dir.rglob("*"):
            if not f.is_file() or f.suffix.lower() not in EMBEDDABLE_EXTS:
                continue
            rel = f.relative_to(ATHENAEUM_ROOT)
            parts = rel.parts
            if len(parts) > 1 and parts[1] in (ARCHIVE_DIR_NAME, DISTILLED_DIR_NAME, SESSIONS_DIR_NAME):
                continue
            if f.name == "INDEX.md":
                continue

            try:
                mtime = f.stat().st_mtime
            except Exception:
                continue

            is_stale = mtime < cutoff

            # If graph is available, check if the file is linked
            is_linked = False
            if graph_available:
                try:
                    import sqlite3
                    conn = sqlite3.connect(str(GRAPH_DB))
                    c = conn.execute(
                        "SELECT id FROM nodes WHERE id = ?",
                        (f"file:{str(rel)}",),
                    )
                    if c.fetchone():
                        is_linked = True
                    conn.close()
                except Exception:
                    pass

            if is_stale and not is_linked:
                result["candidates"].append({
                    "path": str(rel),
                    "codex": codex_name,
                    "last_modified": datetime.fromtimestamp(mtime, tz=timezone.utc).isoformat(),
                    "size": f.stat().st_size,
                })

    # Sort by last_modified (oldest first)
    result["candidates"].sort(key=lambda x: x["last_modified"])

    return result


# ---------------------------------------------------------------------------
# 4. Suggestions loader
# ---------------------------------------------------------------------------


def load_suggestions() -> List[Dict]:
    """Load and clear the pending Codex suggestions queue."""
    if SUGGEST_FILE.exists():
        try:
            suggestions: List[Dict] = json.loads(SUGGEST_FILE.read_text())
            SUGGEST_FILE.write_text("[]")
            return suggestions
        except (json.JSONDecodeError, Exception):
            return []
    return []


# ---------------------------------------------------------------------------
# 5. Mailbox delivery — send report to Hermes
# ---------------------------------------------------------------------------


def _seq_id() -> str:
    """Generate a unique message ID based on timestamp."""
    return datetime.now(timezone.utc).strftime("msg_%Y%m%d_%H%M%S_%f")[:26]


def deliver_to_mailbox(report: HadesReport) -> Optional[str]:
    """Send the Hades report as a JSON message to Hermes' inbox.

    Returns the message file path if delivered, None on failure.
    """
    try:
        HERMES_INBOX.mkdir(parents=True, exist_ok=True)

        msg_id = _seq_id()
        markdown = report.to_markdown()
        health = report.health or {}
        dist = report.distillation or {}
        arch = report.archive or {}

        # Build a concise summary for the body
        summary_parts = []
        if health.get("indexes_created"):
            summary_parts.append(f"📄 Auto-created {len(health['indexes_created'])} INDEX.md files")
        orphans_fs = health.get("orphans", {}).get("fs_unembedded", [])
        if orphans_fs:
            summary_parts.append(f"⚠️ {len(orphans_fs)} files not embedded in ChromaDB")
        if dist.get("distilled_files_written", 0) > 0:
            summary_parts.append(f"🔄 Distilled {dist['distilled_files_written']} files")
        if arch.get("candidates"):
            summary_parts.append(f"🗄️ {len(arch['candidates'])} archive candidates found")
        if report.errors:
            summary_parts.append(f"❌ {len(report.errors)} errors during run")

        summary = " • ".join(summary_parts) if summary_parts else "No issues detected."

        message = {
            "id": msg_id,
            "from": "hephaestus",
            "to": "hermes",
            "type": "report",
            "subject": f"Hades Nightly Report — {report.timestamp[:10]}",
            "body": f"Hades consolidation pipeline ran at {report.timestamp[:19]}.\n\n{summary}\n\n---\n\nFull report:\n{markdown}",
            "priority": "normal",
            "timestamp": report.timestamp,
            "read": False,
            "payload": {
                "report_type": "hades_nightly",
                "date": report.timestamp[:10],
                "indexes_created": len(health.get("indexes_created", [])),
                "files_unembedded": len(orphans_fs),
                "distilled_written": dist.get("distilled_files_written", 0),
                "archive_candidates": len(arch.get("candidates", [])),
                "errors": len(report.errors),
            },
            "thread_id": None,
        }

        msg_path = HERMES_INBOX / f"{msg_id}.json"
        msg_path.write_text(json.dumps(message, indent=2, default=str), encoding="utf-8")
        logger.info("  → Report delivered to Hermes mailbox: %s", msg_path.name)
        return str(msg_path)

    except Exception as exc:
        logger.exception("Failed to deliver report to Hermes mailbox: %s", exc)
        return None


# ---------------------------------------------------------------------------
# 6. Full Hades run
# ---------------------------------------------------------------------------


def run_hades() -> HadesReport:
    """Run the complete Hades consolidation pipeline.

    Returns a HadesReport with all findings.
    """
    report = HadesReport()
    start = time.time()

    try:
        # Phase 1: Health checks
        logger.info("Hades: Running health checks...")
        try:
            health = run_health_checks()
            report.health = health
            logger.info("  → %d codexes checked", len(health.get("codexes", {})))
        except Exception as exc:
            report.errors.append(f"Health checks failed: {exc}")
            logger.exception("Hades health check error")

        # Phase 1b: Embed backfill — fast-embed filesystem files missing from ChromaDB
        logger.info("Hades: Running embed backfill...")
        try:
            embed_result = embed_missing_files()
            report.embed = embed_result
            if embed_result.get("skipped") == -1:
                logger.warning("  → Embedder not available — skipping embed backfill")
            else:
                newly = embed_result.get("embedded", 0)
                before = embed_result.get("total_before", 0)
                after = embed_result.get("total_after", 0)
                rem = embed_result.get("remaining", 0)
                logger.info("  → %d files embedded (total: %d → %d vectors, %d remaining)", newly, before, after, rem)
            _recheck_embedded_counts(report)
            logger.info("  → Report counts refreshed with accurate embed numbers")
        except Exception as exc:
            report.errors.append(f"Embed backfill failed: {exc}")
            logger.exception("Hades embed backfill error")

        # Phase 2: Distillation
        logger.info("Hades: Running distillation...")
        try:
            dist = run_distillation()
            report.distillation = dist
            logger.info("  → %d sessions → %d distilled files",
                         dist.get("sessions_processed", 0),
                         dist.get("distilled_files_written", 0))
        except Exception as exc:
            report.errors.append(f"Distillation failed: {exc}")
            logger.exception("Hades distillation error")

        # Phase 3: Archive scan
        logger.info("Hades: Scanning for archive candidates...")
        try:
            arch = run_archive()
            report.archive = arch
            logger.info("  → %d archive candidates found", len(arch.get("candidates", [])))
        except Exception as exc:
            report.errors.append(f"Archive scan failed: {exc}")
            logger.exception("Hades archive error")

        # Phase 4: Load suggestions
        logger.info("Hades: Loading suggestions...")
        try:
            suggestions = load_suggestions()
            report.suggestions = suggestions
            if suggestions:
                logger.info("  → %d pending Codex suggestions", len(suggestions))
        except Exception as exc:
            report.errors.append(f"Suggestions load failed: {exc}")

        # Phase 5: Deliver report to Hermes mailbox
        logger.info("Hades: Delivering report to Hermes mailbox...")
        try:
            msg_path = deliver_to_mailbox(report)
            if msg_path:
                logger.info("  → Delivered: %s", msg_path)
        except Exception as exc:
            report.errors.append(f"Mailbox delivery failed: {exc}")
            logger.exception("Hades mailbox delivery error")

        elapsed = time.time() - start
        logger.info("Hades complete in %.2fs", elapsed)

        # Phase 6: Write heartbeat for the Fates
        import sys
        _hades_scripts = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "scripts")
        if _hades_scripts not in sys.path:
            sys.path.insert(0, _hades_scripts)
        try:
            from heartbeat import beat  # noqa: F811
            beat("hades")
            logger.info("  → Heartbeat written")
        except Exception as exc:
            logger.warning("  → Heartbeat write failed (non-fatal): %s", exc)

    except Exception as exc:
        report.errors.append(f"Hades run failed: {exc}")
        logger.exception("Hades run failed")

    return report


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------


def main():
    """Run Hades and print the report to stdout."""
    import argparse

    parser = argparse.ArgumentParser(description="Hades — Athenaeum consolidation pipeline")
    parser.add_argument("--health", action="store_true", help="Run health checks only")
    parser.add_argument("--embed", action="store_true", help="Run embed backfill only")
    parser.add_argument("--distill", action="store_true", help="Run distillation only")
    parser.add_argument("--archive", action="store_true", help="Scan archive candidates only")
    parser.add_argument("--json", action="store_true", help="Output as JSON")
    parser.add_argument("--save", metavar="PATH", help="Save report to file")

    args = parser.parse_args()

    # Set up logging
    logging.basicConfig(level=logging.INFO, format="%(levelname)s | %(message)s")

    if args.embed:
        report = HadesReport()
        embed_result = embed_missing_files()
        _recheck_embedded_counts(report)
        if embed_result.get("skipped") == -1:
            print("Embedder not available — skipping")
        else:
            print(f"Embedded: {embed_result.get('embedded', 0)} files "
                  f"(total: {embed_result.get('total_before', 0)} → {embed_result.get('total_after', 0)} vectors)")
        report.health = run_health_checks()
        _recheck_embedded_counts(report)
        report.suggestions = load_suggestions()
    elif args.health:
        report = HadesReport()
        report.health = run_health_checks()
        _recheck_embedded_counts(report)
        report.suggestions = load_suggestions()
    elif args.distill:
        report = HadesReport()
        report.distillation = run_distillation()
    elif args.archive:
        report = HadesReport()
        report.archive = run_archive()
    else:
        report = run_hades()

    # Record heartbeat after any mode runs
    try:
        _hades_scripts = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "scripts")
        if _hades_scripts not in sys.path:
            sys.path.insert(0, _hades_scripts)
        from heartbeat import beat  # noqa: F811
        beat("hades")
    except Exception:
        pass

    if args.json:
        output = json.dumps(report.to_dict(), indent=2)
    else:
        output = report.to_markdown()

    print(output)

    if args.save:
        Path(args.save).write_text(output, encoding="utf-8")
        logger.info("Report saved to %s", args.save)


if __name__ == "__main__":
    main()
