"""Hades — nightly Athenaeum consolidation pipeline.

Runs as a cron job. Performs:
  1. Distillation — extract canonical knowledge from vault sessions
  2. Health checks — ChromaDB vs filesystem consistency, INDEX coverage
  3. Archive management — identify and move stale/unlinked content
  4. Report generation — summary for the 7am delivery
"""

from __future__ import annotations

import json
import logging
import os
import re
import shutil
import time
from collections import defaultdict
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)

_REAL_HOME = os.path.expanduser("~")
ATHENAEUM_ROOT = Path(f"{_REAL_HOME}/athenaeum")
CHROMA_DIR = Path(f"{_REAL_HOME}/.hermes/pantheon/chroma")
GRAPH_DB = Path(f"{_REAL_HOME}/.hermes/pantheon/graph.db")
SUGGEST_FILE = Path(f"{_REAL_HOME}/.hermes/pantheon/suggested-codexes.json")
HERMES_INBOX = Path(f"{_REAL_HOME}/pantheon/gods/messages/hermes")
INDEX_DESCRIPTION = (
    "Content in `{path}` is managed by Demeter and Mnemosyne.\n"
    "Files are auto-detected and embedded into the vector store on change."
)

# Files older than this (in days) are archive candidates if not linked in the graph
STALE_THRESHOLD_DAYS = 90

# Codex exclusion list — system codices we don't auto-archive or auto-distill
SYSTEM_CODEXES = {"Codex-Pantheon", "Codex-Apollo"}

# God memory codices (Codex-God-*) are EXCLUDED from ALL Hades processing.
# These are active living memory — dynamically written by gods, not canonical
# knowledge. The naming convention itself is the exclusion mechanism.
GOD_CODEX_PREFIX = "Codex-God-"

KNOWN_CODEXES = [
    "Codex-Forge", "Codex-Pantheon", "Codex-Infrastructure",
    "Codex-SKC", "Codex-Fiction", "Codex-Asclepius", "Codex-General",
    "Codex-Claude", "Codex-User", "Codex-Work", "Codex-Apollo",
]

EMBEDDABLE_EXTS = {".md", ".txt", ".json", ".yaml", ".yml"}
DISTILLED_DIR_NAME = "distilled"
ARCHIVE_DIR_NAME = "archive"
SESSIONS_DIR_NAME = "sessions"


# ---------------------------------------------------------------------------
# Result container
# ---------------------------------------------------------------------------


class HadesReport:
    """Report generated by a Hades run."""

    def __init__(self):
        self.timestamp: str = datetime.now(timezone.utc).isoformat()
        self.health: Dict[str, Any] = {
            "codexes": {},
            "chroma_vs_fs": {},
            "orphans": {"chroma_only": [], "fs_unembedded": []},
            "missing_indexes": [],
            "stale_candidates": [],
        }
        self.distillation: Dict[str, Any] = {
            "sessions_processed": 0,
            "distilled_files_written": 0,
            "by_codex": {},
        }
        self.archive: Dict[str, Any] = {
            "files_archived": 0,
            "errors": [],
        }
        self.suggestions: List[Dict] = []
        self.extraction: Dict[str, Any] = {
            "files_processed": 0,
            "files_failed": 0,
            "entities_extracted": 0,
            "relations_extracted": 0,
            "error": None,
        }
        self.shared_context: Dict[str, Any] = {
            "decisions_ingested": 0,
            "active_archived": 0,
            "athenaeum_entries": 0,
            "errors": [],
        }
        self.errors: List[str] = []

    def to_dict(self) -> Dict:
        return {
            "timestamp": self.timestamp,
            "health": self.health,
            "distillation": self.distillation,
            "archive": self.archive,
            "extraction": self.extraction,
            "shared_context": self.shared_context,
            "suggestions": self.suggestions,
            "errors": self.errors,
        }

    def to_markdown(self) -> str:
        """Format the report as a human-readable markdown summary."""
        lines = [
            f"# 🌙 Hades Nightly Report — {self.timestamp[:10]}",
            "",
            "## 📊 Codex Overview",
            "| Codex | Files | Embedded | Distilled | Sessions | Missing INDEX |",
            "|---|---|---|---|---|---|",
        ]

        for codex, info in sorted(self.health.get("codexes", {}).items()):
            missing = "⚠️" if codex in self.health.get("missing_indexes", []) else "✅"
            lines.append(
                f"| {codex} | {info.get('files', 0)} | {info.get('embedded', '?')} | "
                f"{info.get('distilled', 0)} | {info.get('sessions', 0)} | {missing} |"
            )

        lines.append("")

        # Chroma vs FS consistency
        orphans_fs = self.health.get("orphans", {}).get("fs_unembedded", [])
        orphans_c = self.health.get("orphans", {}).get("chroma_only", [])
        if orphans_fs or orphans_c:
            lines.append("## ⚠️ Consistency Issues")
            if orphans_fs:
                lines.append(f"- **{len(orphans_fs)} files not embedded in ChromaDB**")
            if orphans_c:
                lines.append(f"- **{len(orphans_c)} ChromaDB entries orphaned** (no matching file)")

        # Missing INDEXes
        missing = self.health.get("missing_indexes", [])
        if missing:
            lines.append(f"\n### Missing INDEX.md ({len(missing)})")
            for m in missing:
                lines.append(f"- {m}")

        # INDEX auto-creation report
        created = self.health.get("indexes_created", [])
        if created:
            lines.append(f"\n### ✅ INDEX.md Auto-Created ({len(created)})")
            for c in created:
                lines.append(f"- `{c}/INDEX.md` created")

        # Stale candidates
        stale = self.health.get("stale_candidates", [])
        if stale:
            lines.append(f"\n### 🗄️ Stale Candidates ({len(stale)})")
            lines.append("Files not modified in 90+ days:")
            for s in stale[:10]:
                lines.append(f"- {s['path']} (last modified: {s['last_modified'][:10]})")
            if len(stale) > 10:
                lines.append(f"- ... and {len(stale) - 10} more")

        # Suggestions
        suggestions = self.suggestions
        if suggestions:
            lines.append(f"\n## 💡 New Codex Suggestions ({len(suggestions)})")
            for s in suggestions:
                lines.append(f"- **{s.get('suggested_codex')}**: {s.get('reason', '')[:100]}")

        # Distillation summary
        dist = self.distillation
        if dist.get("distilled_files_written", 0) > 0:
            lines.append(f"\n## 🔄 Distillation")
            lines.append(f"- Sessions processed: {dist.get('sessions_processed', 0)}")
            lines.append(f"- Distilled files written: {dist.get('distilled_files_written', 0)}")

        # Archive summary
        arch = self.archive
        if arch.get("files_archived", 0) > 0 or len(arch.get("candidates", [])) > 0:
            lines.append("")
            lines.append(f"## 📦 Archive")
            lines.append(f"- Files archived: {arch.get('files_archived', 0)}")
            if arch.get("candidates"):
                lines.append(f"- Candidates found: {len(arch['candidates'])}")

        # Entity extraction summary
        extr = self.extraction
        if extr.get("entities_extracted", 0) > 0 or extr.get("error") or extr.get("status") == "deprecated":
            lines.append("")
            if extr.get("status") == "deprecated":
                lines.append(f"## 🔗 Entity Extraction — ⚠️ Deprecated")
                lines.append(f"- Status: Replaced by {extr.get('replaced_by', 'Ichor Tier A (zero-LLM regex extraction)')}")
                lines.append(f"- See `~/pantheon/ichor-memory-engine-rollout.md` for the Ichor rollout plan")
            elif extr.get("error"):
                lines.append(f"## 🔗 Entity Extraction")
                lines.append(f"- ❌ Error: {extr['error']}")
            else:
                lines.append(f"## 🔗 Entity Extraction")
                lines.append(f"- Files processed: {extr.get('files_processed', 0)}")
                lines.append(f"- Entities extracted: {extr.get('entities_extracted', 0)}")
                lines.append(f"- Relations extracted: {extr.get('relations_extracted', 0)}")
                if extr.get("files_failed", 0) > 0:
                    lines.append(f"- ⚠️ Files failed: {extr['files_failed']}")

        # Shared context sweep summary
        sc = self.shared_context
        if sc.get("decisions_ingested", 0) > 0 or sc.get("active_archived", 0) > 0 or sc.get("athenaeum_entries", 0) > 0:
            lines.append("")
            lines.append(f"## 📋 Shared Context Sweep")
            lines.append(f"- Decisions ingested: {sc.get('decisions_ingested', 0)}")
            lines.append(f"- Active tasks archived: {sc.get('active_archived', 0)}")
            lines.append(f"- Athenaeum write entries noted: {sc.get('athenaeum_entries', 0)}")
            if sc.get("errors"):
                for e in sc["errors"]:
                    lines.append(f"- ⚠️ {e}")
        elif sc.get("errors"):
            lines.append("")
            lines.append(f"## 📋 Shared Context Sweep")
            for e in sc["errors"]:
                lines.append(f"- ⚠️ {e}")

        # Errors
        if self.errors:
            lines.append(f"\n## ❌ Errors ({len(self.errors)})")
            for e in self.errors:
                lines.append(f"- {e}")

        lines.append("")
        lines.append("---")
        lines.append(f"_Report generated: {self.timestamp}_")

        return "\n".join(lines)


# ---------------------------------------------------------------------------
# 1. Health checks
# ---------------------------------------------------------------------------


def _walk_codex_files(codex_root: Path) -> Dict[str, List[Path]]:
    """Walk a Codex directory and group files by subfolder.

    Returns: {
        "files": [all embeddable files excluding archive/distilled/sessions],
        "embeddable": [files that should be in ChromaDB],
        "sessions": [session log files],
        "distilled": [existing distilled files],
        "subdirs": [all subdirectories],
    }
    """
    result: Dict[str, List[Path]] = {
        "files": [],
        "embeddable": [],
        "sessions": [],
        "distilled": [],
        "subdirs": [],
    }

    for child in codex_root.iterdir():
        if child.is_dir():
            result["subdirs"].append(child)

    for f in codex_root.rglob("*"):
        if not f.is_file():
            continue
        ext = f.suffix.lower()
        rel = f.relative_to(codex_root)
        parts = rel.parts

        # Skip hidden files
        if f.name.startswith("."):
            continue
        # Skip INDEX.md — navigation, not content
        if f.name == "INDEX.md":
            continue

        # Categorize by subfolder
        if len(parts) > 1:
            parent = parts[0]
            if parent == ARCHIVE_DIR_NAME:
                continue  # Skip archive files entirely
            if parent == DISTILLED_DIR_NAME:
                result["distilled"].append(f)
                continue
            if parent == SESSIONS_DIR_NAME:
                result["sessions"].append(f)
                continue

        result["files"].append(f)
        if ext in EMBEDDABLE_EXTS:
            result["embeddable"].append(f)

    return result


def ensure_index_files(codex_root: Path) -> List[str]:
    """Auto-create INDEX.md for any subdirectory that's missing one.

    Returns a list of paths where INDEX.md was created.
    Also checks for file counts and content changes.
    """
    created = []
    parent_name = codex_root.name
    parent_rel = f"../INDEX.md"

    for child in sorted(codex_root.iterdir()):
        if not child.is_dir() or child.name.startswith("."):
            continue

        index_path = child / "INDEX.md"
        if index_path.exists():
            continue

        # Count files in this subdirectory
        file_count = sum(1 for f in child.rglob("*") if f.is_file() and not f.name.startswith("."))

        # Generate description
        if child.name == "sessions":
            desc = "Session logs for this Codex."
        elif child.name == "distilled":
            desc = "Distilled knowledge extracted from session logs."
        elif child.name == "archive":
            desc = "Superseded and archived content."
        elif file_count == 0:
            desc = INDEX_DESCRIPTION.format(path=f"`{parent_name}/{child.name}`")
        else:
            desc = INDEX_DESCRIPTION.format(path=f"`{parent_name}/{child.name}`")

        content = (
            f"# {child.name.capitalize()} — Index\n"
            f"Parent: [{parent_name}]({parent_rel})\n\n"
            f"{desc}\n"
        )
        index_path.write_text(content, encoding="utf-8")
        created.append(f"{parent_name}/{child.name}")
        logger.info("  → Created INDEX.md for %s/%s", parent_name, child.name)

    return created


def find_stale_files(
    codex_root: Path, days: int = STALE_THRESHOLD_DAYS
) -> List[Dict]:
    """Find files not modified in *days* that are eligible for archival.

    Skips: INDEX.md, files already in archive/, files in sessions/.
    """
    cutoff = datetime.now(timezone.utc).timestamp() - (days * 86400)
    stale = []

    for f in codex_root.rglob("*"):
        if not f.is_file() or f.suffix.lower() not in EMBEDDABLE_EXTS:
            continue
        rel = f.relative_to(codex_root)
        parts = rel.parts
        if len(parts) > 1 and parts[0] in (ARCHIVE_DIR_NAME, SESSIONS_DIR_NAME, DISTILLED_DIR_NAME):
            continue
        if f.name == "INDEX.md":
            continue

        try:
            mtime = f.stat().st_mtime
            if mtime < cutoff:
                stale.append({
                    "path": str(rel),
                    "last_modified": datetime.fromtimestamp(mtime, tz=timezone.utc).isoformat(),
                    "size": f.stat().st_size,
                })
        except Exception:
            continue

    stale.sort(key=lambda x: x["last_modified"])
    return stale


def run_health_checks() -> Dict[str, Any]:
    """Run all health checks across the Athenaeum.

    Returns health dict matching HadesReport.health shape.
    """
    health: Dict[str, Any] = {
        "codexes": {},
        "chroma_vs_fs": {},
        "orphans": {"chroma_only": [], "fs_unembedded": []},
        "missing_indexes": [],
        "indexes_created": [],
        "stale_candidates": [],
        "chroma_count": None,
    }

    # Try to read ChromaDB for comparison
    chroma_counts: Dict[str, int] = {}
    try:
        import chromadb
        if CHROMA_DIR.is_dir():
            client = chromadb.PersistentClient(path=str(CHROMA_DIR))
            for col in client.list_collections():
                try:
                    name = col.name  # e.g. "pantheon_codex_forge"
                    # Parse the codex name back and normalize to KNOWN_CODEXES casing
                    parts = name.split("_", 2)
                    if len(parts) >= 3:
                        parsed = "Codex-" + parts[2].replace("_", "-")
                        # Case-insensitive match against KNOWN_CODEXES for correct casing
                        matched = next((c for c in KNOWN_CODEXES if c.lower() == parsed.lower()), None)
                        if matched:
                            chroma_counts[matched] = col.count()
                        else:
                            chroma_counts[parsed] = col.count()
                except Exception:
                    pass
        health["chroma_count"] = sum(chroma_counts.values()) if chroma_counts else None
    except ImportError:
        pass  # chromadb not available

    for codex_name in KNOWN_CODEXES:
        codex_dir = ATHENAEUM_ROOT / codex_name
        if not codex_dir.is_dir():
            continue

        info = _walk_codex_files(codex_dir)
        health["codexes"][codex_name] = {
            "files": len(info["files"]),
            "embeddable": len(info["embeddable"]),
            "sessions": len(info["sessions"]),
            "distilled": len(info["distilled"]),
            "subdirs": len(info["subdirs"]),
        }

        # Auto-create INDEX.md for missing subdirectories
        created = ensure_index_files(codex_dir)
        health["indexes_created"].extend(created)

        # Check for persistent gaps (subdirs without INDEX.md despite creation attempt)
        # This catches edge cases like empty dirs or permission issues
        still_missing = []
        for child in codex_dir.iterdir():
            if child.is_dir() and not child.name.startswith("."):
                if not (child / "INDEX.md").exists():
                    still_missing.append(f"{codex_dir.name}/{child.name}")
        if still_missing:
            health["missing_indexes"].extend(still_missing)

        # Chroma vs FS comparison
        embeddable_count = len(info["embeddable"])
        chroma_count = chroma_counts.get(codex_name, 0)
        health["codexes"][codex_name]["embedded"] = chroma_count if chroma_count else 0
        health["chroma_vs_fs"][codex_name] = {
            "chroma": chroma_count,
            "fs_embeddable": embeddable_count,
            "delta": chroma_count - embeddable_count,
        }

        if chroma_count > embeddable_count:
            # Chroma has more than filesystem — some are orphaned
            pass  # Detailed orphan detection requires iterating IDs
        elif embeddable_count > chroma_count:
            for f in info["embeddable"]:
                health["orphans"]["fs_unembedded"].append(str(f.relative_to(ATHENAEUM_ROOT)))
                if len(health["orphans"]["fs_unembedded"]) > 50:
                    break

        # Find stale files
        stale = find_stale_files(codex_dir)
        health["stale_candidates"].extend(stale)

    return health


# ---------------------------------------------------------------------------
# 2. Distillation
# ---------------------------------------------------------------------------


def distill_sessions(codex_name: str, codex_root: Path) -> Dict[str, int]:
    """Extract distilled knowledge from session logs.

    For each session file in codex/sessions/, extracts:
    - Distinct topics mentioned (from markdown headers, bold terms, bullet points)
    - Code blocks
    - Decisions and conclusions (lines after "Decision:", "Conclusion:", etc.)

    Writes a distilled summary to codex/distilled/.
    """
    sessions_dir = codex_root / SESSIONS_DIR_NAME
    distilled_dir = codex_root / DISTILLED_DIR_NAME
    distilled_dir.mkdir(parents=True, exist_ok=True)

    sessions = sorted(sessions_dir.glob("*.md")) if sessions_dir.is_dir() else []
    files_written = 0

    # Known signal patterns for extraction
    topic_pattern = re.compile(r"^#{1,3}\s+(.+)", re.MULTILINE)
    decision_pattern = re.compile(r"^\s*(?:Decision|Conclusion|Result|Outcome|Resolution)\s*[:\-–—]\s*(.+)", re.IGNORECASE | re.MULTILINE)
    bullet_pattern = re.compile(r"^\s*[-*+]\s+(.+)", re.MULTILINE)
    bold_pattern = re.compile(r"\*\*(.+?)\*\*")
    code_block_pattern = re.compile(r"```(\w*)\n(.*?)```", re.DOTALL)

    for session_path in sessions:
        try:
            content = session_path.read_text(encoding="utf-8")
        except Exception:
            continue

        if len(content.strip()) < 200:
            continue  # Skip empty or near-empty sessions

        # Extract metadata from frontmatter
        metadata = {}
        fm_match = re.match(r"^---\n(.*?)\n---", content, re.DOTALL)
        if fm_match:
            for line in fm_match.group(1).strip().split("\n"):
                if ":" in line:
                    k, _, v = line.partition(":")
                    metadata[k.strip()] = v.strip()
            content = content[fm_match.end():]

        # Extract topics (headers)
        topics = []
        for m in topic_pattern.finditer(content):
            t = m.group(1).strip()
            if t and t not in topics:
                topics.append(t)

        # Extract decisions
        decisions = [m.group(1).strip() for m in decision_pattern.finditer(content) if m.group(1).strip()]

        # Extract bold/key terms
        key_terms = list(set(m.group(1) for m in bold_pattern.finditer(content) if m.group(1)))

        # Extract code blocks
        code_blocks = []
        for m in code_block_pattern.finditer(content):
            lang = m.group(1) or "text"
            snippet = m.group(2).strip()
            if snippet:
                code_blocks.append({"language": lang, "content": snippet[:500]})

        # Extract bullet points (first ~20)
        bullets = [m.group(1).strip() for m in bullet_pattern.finditer(content) if m.group(1).strip()][:25]

        if not topics and not decisions and not bullets:
            continue  # Nothing substantive to distill

        # Build distilled document
        session_id = session_path.stem
        lines = [
            f"# Distilled: {session_id}",
            "",
            f"Source: `{codex_name}/{SESSIONS_DIR_NAME}/{session_path.name}`",
            f"Distilled at: {datetime.now(timezone.utc).isoformat()}",
            "",
        ]

        if metadata:
            lines.append("## Metadata")
            for k, v in metadata.items():
                lines.append(f"- **{k}**: {v}")
            lines.append("")

        if topics:
            lines.append(f"## Topics ({len(topics)})")
            for t in topics[:15]:
                lines.append(f"- {t}")
            lines.append("")

        if decisions:
            lines.append(f"## Decisions / Conclusions ({len(decisions)})")
            for d in decisions:
                lines.append(f"- {d}")
            lines.append("")

        if key_terms:
            lines.append(f"## Key Terms ({len(key_terms)})")
            for t in sorted(key_terms)[:20]:
                lines.append(f"- {t}")
            lines.append("")

        if code_blocks:
            lines.append("## Code / Data")
            for cb in code_blocks[:5]:
                lines.append(f"```{cb['language']}")
                lines.append(cb['content'])
                lines.append("```")
                lines.append("")

        if bullets:
            lines.append(f"## Notes ({len(bullets)})")
            for b in bullets[:20]:
                lines.append(f"- {b}")
            lines.append("")

        # Write distilled file
        distilled_name = f"{session_id}--distilled.md"
        distilled_path = distilled_dir / distilled_name
        distilled_path.write_text("\n".join(lines), encoding="utf-8")
        files_written += 1

    return {
        "sessions_processed": len(sessions),
        "distilled_files_written": files_written,
    }


def run_distillation() -> Dict[str, Any]:
    """Run distillation across all Codices with sessions."""
    results: Dict[str, Any] = {
        "sessions_processed": 0,
        "distilled_files_written": 0,
        "by_codex": {},
    }

    for codex_name in KNOWN_CODEXES:
        codex_dir = ATHENAEUM_ROOT / codex_name
        if not codex_dir.is_dir():
            continue

        codex_result = distill_sessions(codex_name, codex_dir)
        results["sessions_processed"] += codex_result.get("sessions_processed", 0)
        results["distilled_files_written"] += codex_result.get("distilled_files_written", 0)
        results["by_codex"][codex_name] = codex_result

    return results


# ---------------------------------------------------------------------------
# 3. Archive management
# ---------------------------------------------------------------------------


def run_archive() -> Dict[str, Any]:
    """Archive stale files that are not linked in the entity graph.

    A file is a candidate if:
    - Not modified in STALE_THRESHOLD_DAYS
    - Not registered as a node in the graph (or has no edges)
    - Not already in archive/ or distilled/

    Currently: reports candidates only, does NOT auto-archive.
    (Auto-archival requires explicit opt-in to avoid data loss.)
    """
    result: Dict[str, Any] = {
        "files_archived": 0,
        "candidates": [],
        "errors": [],
    }

    cutoff = datetime.now(timezone.utc).timestamp() - (STALE_THRESHOLD_DAYS * 86400)

    # Check if graph is available to consult
    graph_available = GRAPH_DB.exists()

    for codex_name in KNOWN_CODEXES:
        codex_dir = ATHENAEUM_ROOT / codex_name
        if not codex_dir.is_dir() or codex_name in SYSTEM_CODEXES:
            continue

        for f in codex_dir.rglob("*"):
            if not f.is_file() or f.suffix.lower() not in EMBEDDABLE_EXTS:
                continue
            rel = f.relative_to(ATHENAEUM_ROOT)
            parts = rel.parts
            if len(parts) > 1 and parts[1] in (ARCHIVE_DIR_NAME, DISTILLED_DIR_NAME, SESSIONS_DIR_NAME):
                continue
            if f.name == "INDEX.md":
                continue

            try:
                mtime = f.stat().st_mtime
            except Exception:
                continue

            is_stale = mtime < cutoff

            # If graph is available, check if the file is linked
            is_linked = False
            if graph_available:
                try:
                    import sqlite3
                    conn = sqlite3.connect(str(GRAPH_DB))
                    c = conn.execute(
                        "SELECT id FROM nodes WHERE id = ?",
                        (f"file:{str(rel)}",),
                    )
                    if c.fetchone():
                        is_linked = True
                    conn.close()
                except Exception:
                    pass

            if is_stale and not is_linked:
                result["candidates"].append({
                    "path": str(rel),
                    "codex": codex_name,
                    "last_modified": datetime.fromtimestamp(mtime, tz=timezone.utc).isoformat(),
                    "size": f.stat().st_size,
                })

    # Sort by last_modified (oldest first)
    result["candidates"].sort(key=lambda x: x["last_modified"])

    return result


# ---------------------------------------------------------------------------
# 4. Suggestions loader
# ---------------------------------------------------------------------------


def load_suggestions() -> List[Dict]:
    """Load and clear the pending Codex suggestions queue."""
    if SUGGEST_FILE.exists():
        try:
            suggestions: List[Dict] = json.loads(SUGGEST_FILE.read_text())
            SUGGEST_FILE.write_text("[]")
            return suggestions
        except (json.JSONDecodeError, Exception):
            return []
    return []


# ---------------------------------------------------------------------------
# 6. Mailbox delivery — send report to Hermes
# ---------------------------------------------------------------------------


def _msg_id() -> str:
    """Generate a unique message ID based on timestamp."""
    return datetime.now(timezone.utc).strftime("msg_%Y%m%d_%H%M%S_%f")[:26]


# ---------------------------------------------------------------------------
# 5. Shared Context Sweep
# ---------------------------------------------------------------------------


SHARED_CONTEXT_ROOT = Path(f"{_REAL_HOME}/pantheon/shared")
SHARED_CUTOFF_HOURS = 24


def run_shared_context_sweep() -> Dict[str, Any]:
    """Scan ~/pantheon/shared/ for entries >24h old and consolidate them.

    Decisions (>24h): Copy to Codex-Pantheon/decisions/ and remove from shared.
    Active tasks (>24h): Move from active/ to archive/ (stale — no longer current).
    athenaeum-writes.md: Already in Athenaeum, just count entries for the report.
    """
    result: Dict[str, Any] = {
        "decisions_ingested": 0,
        "active_archived": 0,
        "athenaeum_entries": 0,
        "errors": [],
    }
    cutoff = datetime.now(timezone.utc) - timedelta(hours=SHARED_CUTOFF_HOURS)

    if not SHARED_CONTEXT_ROOT.is_dir():
        result["errors"].append(f"Shared context root not found: {SHARED_CONTEXT_ROOT}")
        return result

    # ── Sweep decisions/ ──────────────────────────────────────────────
    decisions_dir = SHARED_CONTEXT_ROOT / "decisions"
    if decisions_dir.is_dir():
        decisions_codex = ATHENAEUM_ROOT / "Codex-Pantheon" / "decisions"
        decisions_codex.mkdir(parents=True, exist_ok=True)

        for f in sorted(decisions_dir.glob("*.md")):
            if f.name == "INDEX.md":
                continue
            try:
                mtime = datetime.fromtimestamp(f.stat().st_mtime, tz=timezone.utc)
                if mtime < cutoff:
                    # Copy to Codex-Pantheon/decisions/
                    dest = decisions_codex / f.name
                    shutil.copy2(str(f), str(dest))
                    f.unlink()
                    result["decisions_ingested"] += 1
                    logger.info("  → Ingested decision: %s → Codex-Pantheon/decisions/", f.name)
            except Exception as exc:
                result["errors"].append(f"Failed to process decision {f.name}: {exc}")
                logger.warning("  → Decision sweep error: %s — %s", f.name, exc)

    # ── Sweep active/ ─────────────────────────────────────────────────
    active_dir = SHARED_CONTEXT_ROOT / "active"
    archive_dir = SHARED_CONTEXT_ROOT / "archive"
    archive_dir.mkdir(parents=True, exist_ok=True)

    if active_dir.is_dir():
        for f in sorted(active_dir.glob("*.md")):
            if f.name == "INDEX.md":
                continue
            try:
                mtime = datetime.fromtimestamp(f.stat().st_mtime, tz=timezone.utc)
                if mtime < cutoff:
                    # Move to archive/ — no longer current
                    dest = archive_dir / f.name
                    shutil.move(str(f), str(dest))
                    result["active_archived"] += 1
                    logger.info("  → Archived stale active task: %s", f.name)
            except Exception as exc:
                result["errors"].append(f"Failed to archive active task {f.name}: {exc}")
                logger.warning("  → Active archive error: %s — %s", f.name, exc)

    # ── Count athenaeum-writes.md entries ─────────────────────────────
    aw_path = SHARED_CONTEXT_ROOT / "athenaeum-writes.md"
    if aw_path.exists():
        try:
            content = aw_path.read_text(encoding="utf-8")
            # Count non-header, non-empty lines
            entries = [l for l in content.split("\n") if l.strip() and not l.startswith("#") and not l.startswith("*")]
            result["athenaeum_entries"] = len(entries)
        except Exception as exc:
            result["errors"].append(f"Failed to read athenaeum-writes.md: {exc}")

    return result


def deliver_to_mailbox(report: HadesReport) -> Optional[str]:
    """Send the Hades report as a JSON message to Hermes' inbox.

    Returns the message file path if delivered, None on failure.
    """
    try:
        HERMES_INBOX.mkdir(parents=True, exist_ok=True)

        msg_id = _msg_id()
        markdown = report.to_markdown()
        health = report.health or {}
        dist = report.distillation or {}
        arch = report.archive or {}

        # Build a concise summary for the body
        summary_parts = []
        if health.get("indexes_created"):
            summary_parts.append(f"📄 Auto-created {len(health['indexes_created'])} INDEX.md files")
        orphans_fs = health.get("orphans", {}).get("fs_unembedded", [])
        if orphans_fs:
            summary_parts.append(f"⚠️ {len(orphans_fs)} files not embedded in ChromaDB")
        if dist.get("distilled_files_written", 0) > 0:
            summary_parts.append(f"🔄 Distilled {dist['distilled_files_written']} files")
        if arch.get("candidates"):
            summary_parts.append(f"🗄️ {len(arch['candidates'])} archive candidates found")
        sc = report.shared_context or {}
        if sc.get("decisions_ingested", 0) > 0 or sc.get("active_archived", 0) > 0:
            parts = []
            if sc.get("decisions_ingested"):
                parts.append(f"{sc['decisions_ingested']} decisions")
            if sc.get("active_archived"):
                parts.append(f"{sc['active_archived']} tasks archived")
            summary_parts.append(f"📋 Shared context: {', '.join(parts)}")
        extr = report.extraction or {}
        if extr.get("entities_extracted", 0) > 0:
            summary_parts.append(f"🔗 {extr['entities_extracted']} entities, {extr['relations_extracted']} relations")
        elif extr.get("error"):
            summary_parts.append(f"🔗 Extraction error: {extr['error'][:60]}")
        if report.errors:
            summary_parts.append(f"❌ {len(report.errors)} errors during run")

        summary = " • ".join(summary_parts) if summary_parts else "No issues detected."

        message = {
            "id": msg_id,
            "from": "hephaestus",
            "to": "hermes",
            "type": "report",
            "subject": f"Hades Nightly Report — {report.timestamp[:10]}",
            "body": f"Hades consolidation pipeline ran at {report.timestamp[:19]}.\n\n{summary}\n\n---\n\nFull report:\n{markdown}",
            "priority": "normal",
            "timestamp": report.timestamp,
            "read": False,
            "payload": {
                "report_type": "hades_nightly",
                "date": report.timestamp[:10],
                "indexes_created": len(health.get("indexes_created", [])),
                "files_unembedded": len(orphans_fs),
                "distilled_written": dist.get("distilled_files_written", 0),
                "archive_candidates": len(arch.get("candidates", [])),
                "entities_extracted": extr.get("entities_extracted", 0),
                "relations_extracted": extr.get("relations_extracted", 0),
                "shared_decisions_ingested": sc.get("decisions_ingested", 0),
                "shared_active_archived": sc.get("active_archived", 0),
                "errors": len(report.errors),
            },
            "thread_id": None,
        }

        msg_path = HERMES_INBOX / f"{msg_id}.json"
        msg_path.write_text(json.dumps(message, indent=2, default=str), encoding="utf-8")
        logger.info("  → Report delivered to Hermes mailbox: %s", msg_path.name)
        return str(msg_path)

    except Exception as exc:
        logger.exception("Failed to deliver report to Hermes mailbox: %s", exc)
        return None


# ---------------------------------------------------------------------------
# 7. Full Hades run
# ---------------------------------------------------------------------------


def run_hades() -> HadesReport:
    """Run the complete Hades consolidation pipeline.

    Returns a HadesReport with all findings.
    """
    report = HadesReport()
    start = time.time()

    try:
        # Phase 1: Health checks
        logger.info("Hades: Running health checks...")
        try:
            health = run_health_checks()
            report.health = health
            logger.info("  → %d codexes checked", len(health.get("codexes", {})))
        except Exception as exc:
            report.errors.append(f"Health checks failed: {exc}")
            logger.exception("Hades health check error")

        # Phase 2: Distillation
        logger.info("Hades: Running distillation...")
        try:
            dist = run_distillation()
            report.distillation = dist
            logger.info("  → %d sessions → %d distilled files",
                         dist.get("sessions_processed", 0),
                         dist.get("distilled_files_written", 0))
        except Exception as exc:
            report.errors.append(f"Distillation failed: {exc}")
            logger.exception("Hades distillation error")

        # Phase 3: Archive scan
        logger.info("Hades: Scanning for archive candidates...")
        try:
            arch = run_archive()
            report.archive = arch
            logger.info("  → %d archive candidates found", len(arch.get("candidates", [])))
        except Exception as exc:
            report.errors.append(f"Archive scan failed: {exc}")
            logger.exception("Hades archive error")

        # Phase 4: Shared Context Sweep — ingest >24h entries from ~/pantheon/shared/
        logger.info("Hades: Running shared context sweep...")
        try:
            sc = run_shared_context_sweep()
            report.shared_context = sc
            logger.info("  → %d decisions ingested, %d active tasks archived",
                         sc.get("decisions_ingested", 0),
                         sc.get("active_archived", 0))
            if sc.get("errors"):
                logger.warning("  → %d shared context errors", len(sc["errors"]))
        except Exception as exc:
            report.errors.append(f"Shared context sweep failed: {exc}")
            logger.exception("Hades shared context sweep error")

        # Phase 5: Entity extraction — REPLACED (zero-LLM graph sync is LIVE)
        # LLM-based extraction (extract-entities.py) has been replaced by
        # Ichor Tier A regex extraction (zero-LLM), which now writes directly to
        # graph.db via lib/ichor_tier_a.py → GraphClient.
        logger.info("Hades: Entity extraction — skipping (LLM-based extract-entities.py replaced)")
        logger.info("  → Replaced by Ichor Tier A regex extraction (zero-LLM) — graph write is LIVE")
        report.extraction["status"] = "replaced"
        report.extraction["replaced_by"] = "Ichor Tier A (zero-LLM regex → graph.db)"
        report.extraction["entities_extracted"] = 0
        report.extraction["relations_extracted"] = 0

        # Phase 6: Load suggestions
        logger.info("Hades: Loading suggestions...")
        try:
            suggestions = load_suggestions()
            report.suggestions = suggestions
            if suggestions:
                logger.info("  → %d pending Codex suggestions", len(suggestions))
        except Exception as exc:
            report.errors.append(f"Suggestions load failed: {exc}")

        # Phase 7: Deliver report to Hermes mailbox
        logger.info("Hades: Delivering report to Hermes mailbox...")
        try:
            msg_path = deliver_to_mailbox(report)
            if msg_path:
                logger.info("  → Delivered: %s", msg_path)
        except Exception as exc:
            report.errors.append(f"Mailbox delivery failed: {exc}")
            logger.exception("Hades mailbox delivery error")

        elapsed = time.time() - start
        logger.info("Hades complete in %.2fs", elapsed)

        # Phase 6: Write heartbeat for the Fates
        import sys
        _hades_scripts = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), "scripts")
        if _hades_scripts not in sys.path:
            sys.path.insert(0, _hades_scripts)
        try:
            from heartbeat import beat  # noqa: F811
            beat("hades")
            logger.info("  → Heartbeat written")
        except Exception as exc:
            logger.warning("  → Heartbeat write failed (non-fatal): %s", exc)

    except Exception as exc:
        report.errors.append(f"Hades run failed: {exc}")
        logger.exception("Hades run failed")

    return report


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------


def main():
    """Run Hades and print the report to stdout."""
    import argparse

    parser = argparse.ArgumentParser(description="Hades — Athenaeum consolidation pipeline")
    parser.add_argument("--health", action="store_true", help="Run health checks only")
    parser.add_argument("--distill", action="store_true", help="Run distillation only")
    parser.add_argument("--archive", action="store_true", help="Scan archive candidates only")
    parser.add_argument("--json", action="store_true", help="Output as JSON")
    parser.add_argument("--save", metavar="PATH", help="Save report to file")

    args = parser.parse_args()

    # Set up logging
    logging.basicConfig(level=logging.INFO, format="%(levelname)s | %(message)s")

    if args.health:
        report = HadesReport()
        report.health = run_health_checks()
        report.suggestions = load_suggestions()
    elif args.distill:
        report = HadesReport()
        report.distillation = run_distillation()
    elif args.archive:
        report = HadesReport()
        report.archive = run_archive()
    else:
        report = run_hades()

    # Record heartbeat after any mode runs
    try:
        _hades_scripts = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "scripts")
        if _hades_scripts not in sys.path:
            sys.path.insert(0, _hades_scripts)
        from heartbeat import beat  # noqa: F811
        beat("hades")
    except Exception:
        pass

    if args.json:
        output = json.dumps(report.to_dict(), indent=2)
    else:
        output = report.to_markdown()

    print(output)

    if args.save:
        Path(args.save).write_text(output, encoding="utf-8")
        logger.info("Report saved to %s", args.save)


if __name__ == "__main__":
    main()
