"""Boons API — structured output storage for the Pantheon Boon Drawer.

A boon is a structured output generated by a god during a communion.
Can be promoted to a Forge task or exported."""

from __future__ import annotations

import json
import logging
import os
import uuid
from datetime import datetime, timezone
from typing import Any, List, Optional

logger = logging.getLogger(__name__)

# ── Constants ──────────────────────────────────────────────────────────────

_BOONS_FILE = os.path.expanduser("~/.hermes/pantheon/boons.json")


# ── Data Model ─────────────────────────────────────────────────────────────

# Boon structure:
# {
#   "id": str,              # UUID
#   "type": str,            # "markdown" | "code" | "html" | "image" | "document" | "text"
#   "title": str,           # Short description
#   "body": str,            # Content body
#   "source_god": str,      # God name (e.g. "Hermes", "Hephaestus")
#   "source_communion": str, # Optional communion ID
#   "timestamp": str,       # ISO 8601
#   "pinned": bool,         # Pinned to top?
#   "forge_task_id": str,   # Optional — linked Forge task
#   "format": str           # "markdown" | "html" | "code" | "plain"
# }


def _load_boons() -> list[dict]:
    """Load all boons from JSON file. Returns empty list if file doesn't exist."""
    try:
        if os.path.exists(_BOONS_FILE):
            with open(_BOONS_FILE, "r") as f:
                return json.load(f)
    except (json.JSONDecodeError, OSError) as e:
        logger.warning("Failed to load boons: %s", e)
    return []


def _save_boons(boons: list[dict]) -> bool:
    """Save boons to JSON file. Creates directory if needed."""
    try:
        os.makedirs(os.path.dirname(_BOONS_FILE), exist_ok=True)
        with open(_BOONS_FILE, "w") as f:
            json.dump(boons, f, indent=2)
        return True
    except OSError as e:
        logger.error("Failed to save boons: %s", e)
        return False


# ── CRUD Operations ────────────────────────────────────────────────────────


def list_boons(
    god: str = "",
    pinned_only: bool = False,
    limit: int = 50,
    offset: int = 0,
) -> dict:
    """List boons with optional filtering.

    Args:
        god: Filter by source god (case-insensitive).
        pinned_only: Only return pinned boons.
        limit: Max results to return.
        offset: Pagination offset.

    Returns:
        dict with "boons" list and "total" count.
    """
    boons = _load_boons()

    # Sort by timestamp descending (newest first), pinned first
    boons.sort(key=lambda b: (not b.get("pinned", False), b.get("timestamp", "")), reverse=False)

    if god:
        god_lower = god.lower()
        boons = [b for b in boons if b.get("source_god", "").lower() == god_lower]
    if pinned_only:
        boons = [b for b in boons if b.get("pinned")]

    total = len(boons)
    boons = boons[offset : offset + limit]

    return {"boons": boons, "total": total}


def get_boon(boon_id: str) -> Optional[dict]:
    """Get a single boon by ID."""
    boons = _load_boons()
    for b in boons:
        if b["id"] == boon_id:
            return b
    return None


def create_boon(
    title: str,
    body: str,
    source_god: str,
    type: str = "text",
    format: str = "plain",
    source_communion: str = "",
) -> dict:
    """Create a new boon and persist it.

    Returns the created boon dict.
    """
    boons = _load_boons()

    boon = {
        "id": str(uuid.uuid4()),
        "type": type,
        "format": format,
        "title": title,
        "body": body,
        "source_god": source_god,
        "source_communion": source_communion,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "pinned": False,
        "forge_task_id": "",
    }

    boons.insert(0, boon)  # Newest first
    _save_boons(boons)
    return boon


def update_boon(boon_id: str, updates: dict) -> Optional[dict]:
    """Update fields on an existing boon.

    Allowed fields: title, body, pinned, forge_task_id, type, format.
    Returns updated boon or None if not found.
    """
    allowed = {"title", "body", "pinned", "forge_task_id", "type", "format"}
    boons = _load_boons()
    for b in boons:
        if b["id"] == boon_id:
            for key, value in updates.items():
                if key in allowed:
                    b[key] = value
            _save_boons(boons)
            return b
    return None


def delete_boon(boon_id: str) -> bool:
    """Delete a boon by ID. Returns True if deleted."""
    boons = _load_boons()
    before = len(boons)
    boons = [b for b in boons if b["id"] != boon_id]
    if len(boons) < before:
        _save_boons(boons)
        return True
    return False


def toggle_pin(boon_id: str) -> Optional[dict]:
    """Toggle the pinned state of a boon."""
    boon = get_boon(boon_id)
    if not boon:
        return None
    return update_boon(boon_id, {"pinned": not boon.get("pinned", False)})


def promote_to_forge(boon_id: str, forge_task_id: str = "") -> Optional[dict]:
    """Mark a boon as promoted to a Forge task.

    If no forge_task_id is provided, one is auto-generated.
    """
    if not forge_task_id:
        forge_task_id = f"forge-{uuid.uuid4().hex[:8]}"
    return update_boon(boon_id, {"forge_task_id": forge_task_id})
